//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQLCCCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int Id { get; set; }
        public Nullable<int> Id_sender { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> Date_send { get; set; }
        public string Purport { get; set; }
    
        public virtual citizen citizen { get; set; }
        public virtual citizen citizen1 { get; set; }
    }
}
