//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQLCCCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state_leaders
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Place_of_origin { get; set; }
        public string Role { get; set; }
        public string Photo { get; set; }
    }
}
