//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class criminal_record
    {
        public int Id { get; set; }
        public Nullable<int> Id_citizen { get; set; }
        public string Crime { get; set; }
    
        public virtual citizen citizen { get; set; }
    }
}
